[build]
  # Build command
  command = "npm run build"
  # Output directory
  publish = "dist"

[build.environment]
  # Node version
  NODE_VERSION = "20"

# SPA redirect rule - this handles client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache recipes JSON files for a shorter time
[[headers]]
  for = "/recipes/*.json"
  [headers.values]
    Cache-Control = "public, max-age=3600"
